# Generated by Django 5.1.4 on 2024-12-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('course_target', models.CharField(max_length=100)),
                ('academic_year', models.IntegerField()),
                ('num_students', models.IntegerField()),
                ('faculty_name', models.CharField(max_length=100)),
                ('program_title', models.CharField(max_length=100)),
                ('semester_section', models.CharField(max_length=100)),
                ('max_see_marks', models.IntegerField()),
                ('hod_name', models.CharField(max_length=100)),
            ],
        ),
    ]
