# Generated by Django 5.1.4 on 2024-12-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIEData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10)),
                ('first_ia', models.CharField(max_length=10)),
                ('second_ia', models.CharField(max_length=10)),
                ('third_ia', models.CharField(max_length=10)),
            ],
        ),
    ]
